# Generated by Django 3.0.7 on 2020-06-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctype', models.CharField(max_length=255)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('remark', models.FloatField(blank=True, null=True)),
                ('average_score', models.FloatField(blank=True, null=True)),
                ('average_time', models.FloatField(blank=True, null=True)),
                ('average_upnum', models.IntegerField(blank=True, null=True)),
                ('zip', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('case_id', models.IntegerField()),
                ('up_num', models.IntegerField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('cost_time', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255)),
                ('case_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('code_url', models.CharField(max_length=255)),
                ('score', models.FloatField()),
            ],
            options={
                'db_table': 'upload',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_level', models.IntegerField()),
                ('upload_num', models.IntegerField(blank=True, null=True)),
                ('case_num', models.IntegerField(blank=True, null=True)),
                ('average_score', models.FloatField(blank=True, null=True)),
                ('average_time', models.FloatField(blank=True, null=True)),
                ('average_upnum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
